CMakeLists.txt, include/xsimd/xsimd.hpp, test/CMakeLists.txt, test/copyGTest.cmake.in, test/downloadGTest.cmake.in
Fixes #32 
@ghisvail Let me know if everything is ok for you.
=> cmake files for debian packaging

include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp
=> typo in select fixed (SSE prior to SSE4.1)

test/xsimd_interface_test.cpp
Do not merge until OSX build has finished
=> OSX test fix

include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_neon_bool.hpp, include/xsimd/types/xsimd_neon_int32.hpp, include/xsimd/types/xsimd_neon_int64.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp, test/xsimd_basic_test.hpp
=> traits for bool batches

docs/source/api/available_wrappers.rst, docs/source/api/instr_macros.rst
Only documentation, can be merged without waiting for CI
=> xsimd documentation updated

include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp
=> aligned / unaligned load and store fixed

docs/source/api/xsimd_batch.rst
=> reducers added to the doc

include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_neon_bool.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, test/xsimd_basic_test.hpp
=> fix bool for AVX and SSE

include/xsimd/types/xsimd_traits.hpp, test/xsimd_basic_test.cpp
=> simd_return_type fixed

include/xsimd/types/xsimd_avx512_double.hpp, include/xsimd/types/xsimd_avx512_float.hpp, include/xsimd/types/xsimd_avx512_int32.hpp, include/xsimd/types/xsimd_avx512_int64.hpp, include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_base.hpp, include/xsimd/types/xsimd_neon_int32.hpp, include/xsimd/types/xsimd_neon_int64.hpp, include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp, include/xsimd/types/xsimd_utils.hpp, test/xsimd_basic_test.hpp
This is to check that the unroller works on all compilateurs'
=> add integer modulo and correct division

docs/source/api/available_wrappers.rst
=> warning section for complex support on ARM

benchmark/xsimd_benchmark.hpp, include/xsimd/math/xsimd_math.hpp, include/xsimd/math/xsimd_power.hpp, include/xsimd/math/xsimd_scalar.hpp, test/xsimd_basic_math_test.hpp, test/xsimd_basic_test.hpp, test/xsimd_cexponential_test.hpp, test/xsimd_chyperbolic_test.hpp, test/xsimd_complex_basic_test.hpp, test/xsimd_cpower_test.hpp, test/xsimd_ctrigonometric_test.hpp, test/xsimd_error_gamma_test.hpp, test/xsimd_exponential_test.hpp, test/xsimd_fp_manipulation_test.hpp, test/xsimd_hyperbolic_test.hpp, test/xsimd_power_test.hpp, test/xsimd_rounding_test.hpp, test/xsimd_trigonometric_test.hpp
Provide scalar version for most xsimd functions, with the according
tests.
=> [WIP] scalar mode for xsimd

include/xsimd/types/xsimd_avx_int16.hpp, include/xsimd/types/xsimd_traits.hpp
@serge-sans-paille I hope this is it. I'm checking locally now.
=> add missing traits

include/xsimd/math/xsimd_exponential.hpp, include/xsimd/math/xsimd_fp_sign.hpp, include/xsimd/math/xsimd_math_complex.hpp, include/xsimd/math/xsimd_scalar.hpp, test/xsimd_cexponential_test.hpp
=> Missing functions for complex numbers

include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp
=> store uint16 in sse2 mode fixed

include/xsimd/math/xsimd_basic_math.hpp, include/xsimd/math/xsimd_numerical_constant.hpp, include/xsimd/math/xsimd_scalar.hpp, test/xsimd_basic_math_test.hpp
=> Implemenation of nextafter

include/xsimd/stl/algorithms.hpp, include/xsimd/xsimd.hpp, test/CMakeLists.txt, test/xsimd_algorithms.cpp
A first version of adding support for `xsimd::transform`.
=> add stl-like transform

CMakeLists.txt, examples/CMakeLists.txt, examples/mandelbrot.cpp, examples/pico_bench.hpp
I've got a Cmake for this. 
should I add it so that it adds a new target for the default cmake "examples" or seperate in the examples dir?
=> add mandelbrot example from tsimd

include/xsimd/types/xsimd_avx512_double.hpp, include/xsimd/types/xsimd_avx512_float.hpp, include/xsimd/types/xsimd_avx512_int_base.hpp, include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_avx_int_base.hpp, include/xsimd/types/xsimd_neon_double.hpp, include/xsimd/types/xsimd_neon_float.hpp, include/xsimd/types/xsimd_neon_int16.hpp, include/xsimd/types/xsimd_neon_int32.hpp, include/xsimd/types/xsimd_neon_int64.hpp, include/xsimd/types/xsimd_neon_int8.hpp, include/xsimd/types/xsimd_neon_uint16.hpp, include/xsimd/types/xsimd_neon_uint32.hpp, include/xsimd/types/xsimd_neon_uint64.hpp, include/xsimd/types/xsimd_neon_uint8.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, include/xsimd/types/xsimd_sse_int_base.hpp, test/xsimd_basic_test.hpp
Implementation for batches of complex and batches of bool will be done in dedicated PRs, it involves adding a reference proxy type.
=> operator[] for batches

include/xsimd/types/xsimd_avx512_bool.hpp, include/xsimd/types/xsimd_avx512_conversion.hpp, include/xsimd/types/xsimd_avx_conversion.hpp, include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_avx_int_base.hpp, include/xsimd/types/xsimd_base.hpp, include/xsimd/types/xsimd_fallback.hpp, include/xsimd/types/xsimd_neon_conversion.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, include/xsimd/types/xsimd_sse_int_base.hpp, test/xsimd_algorithms.cpp, test/xsimd_basic_test.hpp
=> bitwise cast from batch_bool to batch

include/xsimd/stl/algorithms.hpp, test/xsimd_algorithms.cpp
=> Fixed reduce on vector smaller than batch

include/xsimd/math/xsimd_rem_pio2.hpp, test/xsimd_cexponential_test.hpp
When released, this will fix https://github.com/QuantStack/xtensor/issues/1539
@serge-sans-paille you might be interested in this small bug fix.
=> Fixed endianness on Windows

include/xsimd/types/xsimd_avx512_double.hpp, include/xsimd/types/xsimd_avx512_float.hpp, include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_base.hpp, include/xsimd/types/xsimd_fallback.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, test/xsimd_basic_test.hpp
=> Fixed haddp

include/xsimd/math/xsimd_scalar.hpp, test/xsimd_test_utils.hpp
Only for scalar mode, let's implement this for complex numbers at some point!
=> Support isinf/isnan for complex number using numpy semantic

include/xsimd/config/xsimd_instruction_set.hpp, include/xsimd/types/xsimd_types_include.hpp
=> #warning -> pragma message(warning:) on MSVC

include/xsimd/types/xsimd_avx512_int16.hpp
=> Fixed typo in intrinsics

include/xsimd/types/xsimd_avx512_int16.hpp
=> Fixed avx512 batch for int16 selection

include/xsimd/types/xsimd_avx512_int16.hpp, include/xsimd/types/xsimd_avx512_int8.hpp
=> Fixed select for int8 and int16 with avx512bw instruction set

include/xsimd/types/xsimd_avx512_int_base.hpp
=> Fixed conversion warnings

include/xsimd/types/xsimd_avx512_int16.hpp, include/xsimd/types/xsimd_avx512_int8.hpp
=> Fixed avx512_fallback_batch_bool

.travis.yml, include/xsimd/types/xsimd_avx512_int32.hpp, include/xsimd/types/xsimd_avx512_int64.hpp, test/xsimd_cpower_test.cpp
=> Fixed avx512 shift operators

include/xsimd/types/xsimd_traits.hpp, test/xsimd_api_test.hpp
As opposed to unsigned char (uint8_t) and signed chars (int8_t).
=> Support vector of char

include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, test/xsimd_basic_test.hpp
=> corrected lt for unsigned integers

include/xsimd/types/xsimd_avx512_double.hpp, include/xsimd/types/xsimd_avx512_float.hpp, include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_avx_int_base.hpp, include/xsimd/types/xsimd_base.hpp, include/xsimd/types/xsimd_fallback.hpp, include/xsimd/types/xsimd_neon_double.hpp, include/xsimd/types/xsimd_neon_float.hpp, include/xsimd/types/xsimd_neon_int16.hpp, include/xsimd/types/xsimd_neon_int32.hpp, include/xsimd/types/xsimd_neon_int64.hpp, include/xsimd/types/xsimd_neon_int8.hpp, include/xsimd/types/xsimd_neon_uint16.hpp, include/xsimd/types/xsimd_neon_uint32.hpp, include/xsimd/types/xsimd_neon_uint64.hpp, include/xsimd/types/xsimd_neon_uint8.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, include/xsimd/types/xsimd_sse_int_base.hpp, test/xsimd_basic_test.hpp
=> Initialization from batch_bool for FP batches

benchmark/main.cpp, benchmark/xsimd_benchmark.hpp, include/xsimd/math/xsimd_estrin.hpp, include/xsimd/math/xsimd_horner.hpp, test/CMakeLists.txt, test/xsimd_poly_evaluation_test.cpp, test/xsimd_poly_evaluation_test.hpp
[Estrin's scheme](https://en.wikipedia.org/wiki/Estrin%27s_scheme) is a scheme for evaluating polynomials that trades off a bit ofperformance in exchange for serialization. This scheme performs more operations but a lot of them are independent so can be computed in parallel.
  | poly size | scheme | time (ms) | scheme | time (ms) | time(estrin) / time(horner)
-- | -- | -- | -- | -- | -- | --
sse float | 5 | horner | 0.003486 | estrin | 0.004268 | 1.224325875
sse float | 10 | horner | 0.008255 | estrin | 0.008526 | 1.032828589
sse float | 12 | horner | 0.011291 | estrin | 0.009748 | 0.8633424852
sse float | 14 | horner | 0.014908 | estrin | 0.011331 | 0.7600617118
sse float | 16 | horner | 0.018735 | estrin | 0.012223 | 0.6524152655
sse double unr | 5 | horner | 0.0053 | estrin | 0.008386 …
=> Add Estrin's evaluation scheme for polynomials

include/xsimd/math/xsimd_estrin.hpp
=> Added missing include in xsimd_estrin.hpp

include/xsimd/types/xsimd_avx_int16.hpp
=> Fixed select for batch of int16 in avx2

include/xsimd/memory/xsimd_load_store.hpp
=> xsimd_load_store.hpp: Fixed a minor issue in testing for disabled xsimd

CMakeLists.txt, test/CMakeLists.txt
This is a minor PR that improves the integration of testing and specifically of GTest. It brings better compatibility with FindGTest from (future) cmake.
Please let me know if it would need more motivation? :-)
=> CMake: Modernized GTest-integration

docs/environment.yml, docs/source/api/basic_functions.rst, docs/source/api/classification_functions.rst, docs/source/api/exponential_functions.rst, docs/source/api/hyperbolic_functions.rst, docs/source/api/nearint_operations.rst, docs/source/api/power_functions.rst, docs/source/api/trigonometric_functions.rst
=> Fixed documentation of overloads

include/xsimd/config/xsimd_instruction_set.hpp
=> Fixed AVX512 detection with clang

include/xsimd/types/xsimd_base.hpp, test/test_batch.cpp
=> Added broadcast / from_aligned / form_unaligned static methods

docs/source/index.rst
=> Fixed C++ level required

.azure-pipelines/unix-build.yml, include/xsimd/config/xsimd_instruction_set.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_base_constant.hpp, include/xsimd/types/xsimd_fallback.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_types_include.hpp, test/CMakeLists.txt, test/test_algorithms.cpp, test/test_basic_math.cpp, test/test_batch_int.cpp, test/test_utils.hpp
=> Add -Werror mode and use it for testing

docs/source/api/xsimd_batch.hpp
=> Fixed batch constructor doc

include/xsimd/math/xsimd_math_complex.hpp, include/xsimd/math/xsimd_scalar.hpp, test/test_batch_complex.cpp
=> Support and test fma, fma and fmna for complex number

.azure-pipelines/azure-pipelines-linux-gcc.yml
Thie PR fixes the issue on Azure due to the recente changes described [here](https://github.com/actions/virtual-environments/issues/2950)
=> Manually installed gcc 7 and gcc 8 on Azure

include/xsimd/types/xsimd_complex_base.hpp, test/test_batch_complex.cpp
=> Support loading / storing complex numbers with empty imaginary part

CMakeLists.txt
=> Fix header dependencies

include/xsimd/config/xsimd_align.hpp, include/xsimd/memory/xsimd_aligned_allocator.hpp
Detect invalid alignment under debug mode.
Use platform allocator.
=> Improve aligned allocator implementation

docs/Doxyfile, docs/source/api/batch_index.rst, docs/source/api/data_transfer.rst, docs/source/basic_usage.rst, docs/source/index.rst, docs/source/installation.rst, docs/source/vectorized_code.rst, include/xsimd/types/xsimd_api.hpp, include/xsimd/types/xsimd_batch.hpp
- explicitly document the dispatching system
- more cross reference
- typo fixes
- and many small details like tag dispatching mechanism...
=> Improve generated doc

include/xsimd/arch/generic/xsimd_generic_math.hpp
=> Make nearbyhint generic implementation compatible with -ffast-math

include/xsimd/arch/xsimd_sse3.hpp
Fixes https://github.com/xtensor-stack/xsimd/issues/556
=> Leverage _mm_lddqu_si128 for sse3 and above arch

include/xsimd/arch/xsimd_neon64.hpp
=> Faster implementation of xsimd::all on aarch64

include/xsimd/types/xsimd_utils.hpp
So that it can be used for make_index_sequence and make_int_sequence.
=> Make make_integer_sequence generic

include/xsimd/types/xsimd_batch.hpp, test/test_batch_complex.cpp
=> Implemented operator! for batch of complex

include/xsimd/arch/generic/xsimd_generic_complex.hpp
Shorter and easier to maintain, the code is.
\- Darth Simdious \-
=> Simplified implementation of basic complex functions

include/xsimd/types/xsimd_batch.hpp
=> Assert when using incomplete initializer_list

include/xsimd/arch/generic/xsimd_generic_arithmetic.hpp, include/xsimd/arch/generic/xsimd_generic_complex.hpp, include/xsimd/arch/generic/xsimd_generic_details.hpp, include/xsimd/arch/generic/xsimd_generic_logical.hpp, include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/generic/xsimd_generic_rounding.hpp, include/xsimd/arch/generic/xsimd_generic_trigo.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx2.hpp, include/xsimd/arch/xsimd_avx512bw.hpp, include/xsimd/arch/xsimd_avx512dq.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_constants.hpp, include/xsimd/arch/xsimd_fma3.hpp, include/xsimd/arch/xsimd_fma4.hpp, include/xsimd/arch/xsimd_fma5.hpp, include/xsimd/arch/xsimd_generic_fwd.hpp, include/xsimd/arch/xsimd_neon.hpp, include/xsimd/arch/xsimd_neon64.hpp, include/xsimd/arch/xsimd_scalar.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/arch/xsimd_sse3.hpp, include/xsimd/arch/xsimd_sse4_1.hpp, include/xsimd/arch/xsimd_sse4_2.hpp, include/xsimd/arch/xsimd_ssse3.hpp, include/xsimd/types/xsimd_api.hpp, include/xsimd/types/xsimd_batch.hpp, include/xsimd/types/xsimd_batch_constant.hpp, include/xsimd/types/xsimd_utils.hpp
- it helps the optimizer
- it prevents regression like #617
=> Mark all functions inline

include/xsimd/types/xsimd_batch.hpp, test/test_batch_bool.cpp
=> Support logical xort for batch bool

include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx2.hpp, include/xsimd/arch/xsimd_avx512dq.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_neon.hpp, include/xsimd/arch/xsimd_neon64.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/arch/xsimd_sse4_1.hpp, include/xsimd/types/xsimd_api.hpp
=> Provide better  conversion functions

include/xsimd/arch/xsimd_neon.hpp, include/xsimd/arch/xsimd_neon64.hpp
=> NEON: Improve any/all

docs/source/api/basic_functions.rst, docs/source/api/batch_manip.rst, docs/source/api/power_functions.rst
thanks to @klagrassa and her comrade for spotting this.
=> Fix some ambiguous doxygen reference

docs/Doxyfile, docs/source/api/batch_index.rst, docs/source/api/xsimd_batch_constant.rst, include/xsimd/types/xsimd_api.hpp, include/xsimd/types/xsimd_batch_constant.hpp, include/xsimd/types/xsimd_generic_arch.hpp
=> Document batch_constant

include/xsimd/arch/generic/xsimd_generic_math.hpp, test/test_power.cpp, test/test_utils.hpp
=> Make xsimd::pow implementation resilient to FE_INVALID

.azure-pipelines/azure-pipelines-win.yml, include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/arch/xsimd_sse4_1.hpp, include/xsimd/types/xsimd_api.hpp, include/xsimd/types/xsimd_utils.hpp, test/CMakeLists.txt, test/test_batch_manip.cpp
=> Provide xsimd::insert to modify a single value from a vector

include/xsimd/arch/xsimd_neon.hpp, include/xsimd/arch/xsimd_neon64.hpp, include/xsimd/types/xsimd_api.hpp, test/test_batch_manip.cpp, test/test_utils.hpp
~~This PR is not ready yet, I will rebase it when #649 is merged so it can leverage the tests.
This is mainly for review and discussion.~~
Rebase done.
=> Implemented swizzle for neon and neon64

test/CMakeLists.txt
Signed-off-by: Wei Fu <wefu@redhat.com>
=> Enable riscv64 in build system

include/xsimd/types/xsimd_api.hpp
=> Fix ambiguous call since C++20

README.md
=> Fix architecture list in README

include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_neon.hpp, include/xsimd/arch/xsimd_neon64.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/types/xsimd_api.hpp, test/test_batch_float.cpp, test/test_utils.hpp
:wave:
As requested in #706, this is the first function from my Krita work.
I've added tests to account for the documented precision in Intel Intrinsics Manual.
=> Add xsimd::reciprocal

.github/workflows/benchmark.yml, examples/mandelbrot.cpp
Interestingly, 87675f38a013a8b11373bb32e1a8ed3a69be6691 uncovered a regression
in the example.
Fix #709
=> Fix and validate benchmarks

include/xsimd/arch/xsimd_neon.hpp
=> insert: add NEON support

include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/arch/xsimd_sse4_1.hpp
=> Fix integer sign during shift

.azure-pipelines/azure-pipelines-linux-clang.yml, .azure-pipelines/azure-pipelines-linux-gcc.yml, .azure-pipelines/unix-build.yml, include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_neon.hpp, test/test_batch_manip.cpp, test/test_load_store.cpp, test/test_rounding.cpp, test/test_utils.hpp
=> Fix CI setup

include/xsimd/types/xsimd_batch.hpp
=> Harmonize std::initializer_list check

include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/types/xsimd_api.hpp, test/test_batch_float.cpp
=> Activate xsmd::rsqrt tests

include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/types/xsimd_api.hpp, test/test_batch_complex.cpp
Intended to be the equivalent of `std::polar()`
=> Add xsimd::polar()

include/xsimd/arch/xsimd_neon.hpp
👋 
Dmitry Kazakov from our team noticed that we hadn't implemented intrinsics-backed scalar rounding for Arm. Our case was for single-values only, but it also applies for the `nearbyint_as_int` function that I upstreamed here.
This PR implements `nearbyint_as_int` for F32->I32 under Neon. This code is based on the sse2neon project, as credited in the diff.
=> Implement nearbyint_as_int for NEON

include/xsimd/arch/xsimd_neon.hpp, include/xsimd/types/xsimd_api.hpp, test/test_shuffle.cpp
:wave:
This PR completes the implementation of slides for integer batches.
Fixes #636
=> Implement slides for NEON

docs/source/api/dispatching.rst
These two things weren't showing up properly on the docs.
=> Made a minor docs syntax fix.

CMakeLists.txt
Fixed a minor spelling error (the word only has [one 'n'](https://en.wikipedia.org/wiki/Software_versioning)).
=> Fixed a typo.

include/xsimd/arch/xsimd_neon.hpp, include/xsimd/types/xsimd_batch.hpp, test/test_batch.cpp, test/test_batch_bool.cpp, test/test_batch_complex.cpp, test/test_batch_int.cpp
=> Harmonize initialization between batch(scalar) and batch{scalar}

docs/source/index.rst, examples/mandelbrot.cpp, include/xsimd/arch/generic/xsimd_generic_details.hpp, include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_neon.hpp, include/xsimd/arch/xsimd_neon64.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/types/xsimd_api.hpp, test/test_batch_cast.cpp
=> Replace `bool_cast` by `batch_bool_cast` and harmonize / test usage

include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx2.hpp, include/xsimd/arch/xsimd_avx512bw.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/arch/xsimd_sse4_1.hpp, include/xsimd/arch/xsimd_ssse3.hpp, include/xsimd/xsimd.hpp
Fixed #779, as per the discussions.
=> Converted the `switch` statements to `XSIMD_IF_CONSTEXPR`

benchmark/xsimd_benchmark.hpp, include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx2.hpp, include/xsimd/arch/xsimd_avx512dq.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_neon.hpp, include/xsimd/arch/xsimd_scalar.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/types/xsimd_api.hpp, test/CMakeLists.txt, test/test_poly_evaluation.cpp, test/test_utils.hpp, test/test_xsimd_api.cpp
=> Test and fill holes in xsimd scalar api

docs/source/migration_guide.rst, include/xsimd/types/xsimd_api.hpp, include/xsimd/types/xsimd_batch.hpp, include/xsimd/types/xsimd_neon_register.hpp, include/xsimd/types/xsimd_register.hpp, include/xsimd/types/xsimd_traits.hpp, test/test_api.cpp, test/test_arch.cpp, test/test_load_store.cpp, test/test_utils.hpp
=> Properly report unsupported double for neon

test/test_batch_complex.cpp
=> Use properly aligned array during xtl testing

.github/workflows/cross-sve.yml, README.md
FUJITSU A64FX does supports SVE512.
=> Add SVE512 CI job

test/test_batch_bool.cpp
=> Test support for xsimd::bitwise_not on batch_bool

test/test_batch.cpp, test/test_batch_bool.cpp
=> Properly test batch and batch_bool constructors

.github/workflows/cross.yml, .github/workflows/linux.yml
=> Test sse3 support

include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_avx512bw.hpp, include/xsimd/arch/xsimd_avx512f.hpp
=> Some avx512 bugfixes

include/xsimd/arch/xsimd_scalar.hpp
On android builds this section is causing build errors, just wondering if this is the best solution?
=> Fix for android builds

docs/source/api/batch_manip.rst, include/xsimd/types/xsimd_api.hpp
Fix xs::select output and add forgotten conversion functions
=> Improve documentation generation

include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_sse2.hpp
=> Faster alternate implementation of batch_bool compare

.github/workflows/windows.yml, include/xsimd/config/xsimd_config.hpp
=> MSVC doesn't have a way to force sse3 / sse3 / sse4.x arch

include/xsimd/arch/xsimd_avx512f.hpp
=> Provide avx512f implementation of FMA and variant

Changelog.rst
=> Add changelog, tracing changes back to 8.0.1

include/xsimd/arch/generic/xsimd_generic_details.hpp, include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx2.hpp, include/xsimd/arch/xsimd_avx512bw.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_neon.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/arch/xsimd_ssse3.hpp, include/xsimd/types/xsimd_api.hpp, test/test_bitwise_cast.cpp, test/test_conversion.cpp
Take a scalar as parameter instead of a batch.
=> Change bitwise_cast API

docs/source/api/arch.rst, docs/source/api/dispatching.rst, include/xsimd/config/xsimd_arch.hpp, include/xsimd/types/xsimd_avx2_register.hpp, include/xsimd/types/xsimd_avx512bw_register.hpp, include/xsimd/types/xsimd_avx512cd_register.hpp, include/xsimd/types/xsimd_avx512dq_register.hpp, include/xsimd/types/xsimd_avx512f_register.hpp, include/xsimd/types/xsimd_avx_register.hpp, include/xsimd/types/xsimd_fma3_avx2_register.hpp, include/xsimd/types/xsimd_fma3_avx_register.hpp, include/xsimd/types/xsimd_fma3_sse_register.hpp, include/xsimd/types/xsimd_fma4_register.hpp, include/xsimd/types/xsimd_generic_arch.hpp, include/xsimd/types/xsimd_neon64_register.hpp, include/xsimd/types/xsimd_neon_register.hpp, include/xsimd/types/xsimd_sse2_register.hpp, include/xsimd/types/xsimd_sse3_register.hpp, include/xsimd/types/xsimd_sse4_1_register.hpp, include/xsimd/types/xsimd_sse4_2_register.hpp, include/xsimd/types/xsimd_ssse3_register.hpp, include/xsimd/types/xsimd_sve_register.hpp, test/test_arch.cpp
=> Introduce and document xsimd::best_arch

include/xsimd/arch/xsimd_scalar.hpp, test/test_xsimd_api.cpp
=> Provide and test scalar version f xsimd::all xsimd::none and xsimd::any

include/xsimd/config/xsimd_cpuid.hpp
Fixes #911 
cc @serge-sans-paille
=> Fixed AVX detection

.github/workflows/macos.yml, docs/source/api/dispatching.rst, docs/source/basic_usage.rst, docs/source/vectorized_code.rst, test/CMakeLists.txt, test/doc/CMakeLists.txt, test/doc/explicit_use_of_an_instruction_set.cpp, test/doc/explicit_use_of_an_instruction_set_mean.cpp, test/doc/explicit_use_of_an_instruction_set_mean_aligned.cpp, test/doc/explicit_use_of_an_instruction_set_mean_arch_independent.cpp, test/doc/explicit_use_of_an_instruction_set_mean_tag_dispatch.cpp, test/doc/manipulating_abstract_batches.cpp, test/doc/manipulating_parametric_batches.cpp, test/doc/sum.hpp, test/doc/sum_avx2.cpp, test/doc/sum_sse2.cpp, test/doc/writing_vectorized_code.cpp
That way we won't regress on documentation, which is always a plus.
=> Setup testing of documentation example

.github/workflows/linux.yml, include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/types/xsimd_api.hpp, test/test_shuffle.cpp
=> Provide xsimd::shuffle of floating point batches

include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx2.hpp, include/xsimd/arch/xsimd_avx512bw.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_neon64.hpp, include/xsimd/arch/xsimd_ssse3.hpp, include/xsimd/arch/xsimd_sve.hpp, include/xsimd/types/xsimd_api.hpp, test/test_batch_manip.cpp
Also provide some specialization for available architectures.
=> Provide a generic implementation of xsimd::swizzle with dynamic indices

include/xsimd/arch/generic/xsimd_generic_math.hpp, test/test_xsimd_api.cpp
Kudos to Joël Falcou for helping out on that one.
Fix #936
=> Fix erfc implementation

docs/source/api/arch.rst, docs/source/vectorized_code.rst
These are a couple documentation mistakes I came across while going through the docs.
=> Fixing some documentation mistakes

README.md
Mentions to Firefox, Arrow, Krita.
=> Update readme with a section on adoption, and a section on the history of the project

include/xsimd/config/xsimd_arch.hpp, include/xsimd/config/xsimd_cpuid.hpp, include/xsimd/types/xsimd_generic_arch.hpp, include/xsimd/types/xsimd_rvv_register.hpp, include/xsimd/types/xsimd_sve_register.hpp, test/test_arch.cpp
Traverse required arch in the order provided by the user instead of trying to guess the best one.
It is actually impossible to define the notion of a best architectures as intel instruction set have a tree structure and not a linear structure : there are multiple leaves and none of them can be considered the "best".
=> Fix dispatching mechanism

include/xsimd/arch/generic/xsimd_generic_math.hpp, test/test_power.cpp
=> Test and fix 0^-x

.github/workflows/emulated.yml, docs/source/api/arch.rst, include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_emulated.hpp, include/xsimd/arch/xsimd_isa.hpp, include/xsimd/arch/xsimd_scalar.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/types/xsimd_all_registers.hpp, include/xsimd/types/xsimd_api.hpp, include/xsimd/types/xsimd_emulated_register.hpp, test/test_arch.cpp, test/test_batch_bool.cpp, test/test_custom_default_arch.cpp, test/test_memory.cpp, test/test_xsimd_api.cpp
=> Add support form emulated<N> arch

docs/environment.yml
This should fix the rtd build.
=> Added sphinx 6 to docs environment file

include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_ssse3.hpp, test/test_shuffle.cpp
=> Implement [u]int8 and [u]int16 matrix transpose for 128 bit registers

include/xsimd/arch/generic/xsimd_generic_memory.hpp, test/test_api.cpp
@serge-sans-paille we missed that one ;)
=> Fixed kernel::store for booleans

include/xsimd/arch/xsimd_avx512vbmi.hpp
As is the title, passed test-xsimd with -mavx512vbmi option
=> Add slide_left&slide_right for avx512vbmi

CMakeLists.txt
=> Bump xtl dependency requirement

include/xsimd/types/xsimd_api.hpp
=> Make sure shuffle and swizzle constant mask indices are unsigned

include/xsimd/arch/xsimd_neon.hpp
Use the same approach as #1172
=> Optimize loading of batch_bool from memory on arm
