xtensor-stack/xsimd

include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp
These functions are called in the corresponding xexpressions when xtensor is compiled with `XTENSOR_USE_SIMD=ON`. Specifically, tests `left_shift` and `right_shift` in `test_xoperation.cpp` fail to compile. The PR is not pretty, but seems to be the simplest solution by far.
=> added missing operator<<(batch, batch) and operator>>(batch, batch)

include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_base.hpp, include/xsimd/types/xsimd_neon_bool.hpp, include/xsimd/types/xsimd_neon_double.hpp, include/xsimd/types/xsimd_neon_float.hpp, include/xsimd/types/xsimd_neon_int32.hpp, include/xsimd/types/xsimd_neon_int64.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp, test/xsimd_basic_test.hpp
These operators, even if not called, are required by some compilers to compile the test suite of `xtensor` with SIMD enabled.
=> generic logical operators

CMakeLists.txt, benchmark/xsimd_benchmark.hpp, docs/source/api/available_wrappers.rst, include/xsimd/math/xsimd_rounding.hpp, include/xsimd/types/xsimd_avx_conversion.hpp, include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_base.hpp, include/xsimd/types/xsimd_fallback.hpp, include/xsimd/types/xsimd_neon_bool.hpp, include/xsimd/types/xsimd_neon_conversion.hpp, include/xsimd/types/xsimd_sse_conversion.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp, include/xsimd/types/xsimd_types_include.hpp, include/xsimd/types/xsimd_utils.hpp, test/xsimd_basic_math_test.cpp, test/xsimd_basic_test.cpp, test/xsimd_error_gamma_test.cpp, test/xsimd_exponential_test.cpp, test/xsimd_fp_manipulation_test.cpp, test/xsimd_hyperbolic_test.cpp, test/xsimd_power_test.cpp, test/xsimd_rounding_test.cpp, test/xsimd_trigonometric_test.cpp
This MR strives to be a hack-free version of #88 . It is mostly a rewrite, using the existing branch as inspiration when things go wrong. The end goal is to get a fallback version of `batch<T, N>` which compiles down to scalar loops, that may or may not be autovectorized by the compiler.
While I was at it, I also cleaned a couple of minor things along the way, such as the inability to print or query batch_bool.
Current status:
=> Cleaned up version of the fallback batch type

.travis.yml
@HadrienG2 let's activate it on gcc6 only for now, that should be enough.
=> fallback batch enabled in ci

include/xsimd/types/xsimd_neon_float.hpp, test/xsimd_test_utils.hpp
This PR increases the approximation accuracy for calculating the square root of a floating point number on pre-ARMv8 hardware. 
It helps to alleviate accuracy problems we've observed in the complex implementation. 
The remaining failing test is `complex tan`.
=> increase NEON float accuracy for sqrt

include/xsimd/types/xsimd_avx512_int8.hpp
I was mucking around with compiler flags on an AVX512 machine and spotted what look like a couple of cases of missing semicolons on class template specialisations.
=> Fix missing semicolons.

.appveyor.yml, .travis.yml, CMakeLists.txt, README.md
This facilitates the `make install` feature. If the tests are build one has to worry about `gtest` which could be a nuisance if one just wants to install the header-only library.
=> Changed default cmake behavior to not build the tests

include/xsimd/math/xsimd_numerical_constant.hpp, include/xsimd/types/xsimd_neon_int32.hpp
Hello
I became aware of xsimd through godbolt, and I wanted to see if I could use the compiler explorer to look at some generated assembly for an ARM Cortex-M7 target. The following however does not compile:
https://godbolt.org/z/LRw7w8
The issues are ambiguous function calls between
1. `inline batch<int32_t, 4>::batch` with `const int32_t*` vs `int32_t`
2. Calls to `generic_caster` through expansions of `XSIMD_DEFINE_CONSTANT_HEX`
For 1. I explicitly cast to `int32_t` since the pointer overload calls `vld1q_s32` which, if `0` were replaced with `nullptr`, would load from a null pointer? For 2. I cast to `uint32_t` just to complement what's done in the `DOUBLE` case.
Hopefully I've correctly understood the intention for both. 
With these changes, and adding `-flax-vector-conversions` as …
=> Disambiguate function calls for ARM NEON

include/xsimd/types/xsimd_avx_int16.hpp, include/xsimd/types/xsimd_avx_int8.hpp, include/xsimd/types/xsimd_neon_int8.hpp, include/xsimd/types/xsimd_neon_uint8.hpp, test/xsimd_basic_test.hpp
There was a bug with the lower-than operator for int8 & int16 types.
And removes usage of _mm256_xor_si256 from `AVX` (note the missing `2`) which did not compile /cc @serge-sans-paille 
additionally, this adds some more tests (also for the constructors from multiple values, incl. min/max of the int type).
=> add more int tests

include/xsimd/math/xsimd_rem_pio2.hpp
#178 
renaming `__LITTLE_ENDIAN` and attempting to detect on common platforms and compilers: windows, gcc, clang.
By no means I expect this detection to be exhaustive, but I hope it covers a good deal.
Little endianness would not be detected on Linux OS prior.
=> Fix about endianness detection, support more platforms

include/xsimd/types/xsimd_avx512_double.hpp, include/xsimd/types/xsimd_avx512_float.hpp, include/xsimd/types/xsimd_avx512_int16.hpp, include/xsimd/types/xsimd_avx512_int32.hpp, include/xsimd/types/xsimd_avx512_int64.hpp, include/xsimd/types/xsimd_avx512_int8.hpp, include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_avx_int16.hpp, include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_avx_int8.hpp, include/xsimd/types/xsimd_base.hpp, include/xsimd/types/xsimd_fallback.hpp, include/xsimd/types/xsimd_neon_double.hpp, include/xsimd/types/xsimd_neon_float.hpp, include/xsimd/types/xsimd_neon_int16.hpp, include/xsimd/types/xsimd_neon_int32.hpp, include/xsimd/types/xsimd_neon_int64.hpp, include/xsimd/types/xsimd_neon_int8.hpp, include/xsimd/types/xsimd_neon_uint16.hpp, include/xsimd/types/xsimd_neon_uint32.hpp, include/xsimd/types/xsimd_neon_uint64.hpp, include/xsimd/types/xsimd_neon_uint8.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, include/xsimd/types/xsimd_sse_int16.hpp, include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp, include/xsimd/types/xsimd_sse_int8.hpp
With this patch, -Wpedantic no longer produces warnings.
=> Eliminate unnecessary semicolons in macros.

include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, test/xsimd_basic_test.hpp
Hi there,
Many thanks for your fantastic library !
There's a small correction for `batch_bool<T,...>::operator[]` where `T` is a `float` or a `double`: sse and avx operations that give booleans (e.g. for `operator<`) actually fill all the bits in the results. If direclty read as a `double` or a `float`, it gives a `-nan` for a `true` or a `0` for a `false`, and unfortunately, these floating points values do not convert directly to the right boolean values :(
In the PR, there are some additionnal tests for this topic.
Best regards.
=> correction for batch_bool<T,.>::operator[] for avx/sse double/float

include/xsimd/types/xsimd_neon_int16.hpp, include/xsimd/types/xsimd_neon_int8.hpp, include/xsimd/types/xsimd_neon_uint16.hpp, include/xsimd/types/xsimd_neon_uint64.hpp, include/xsimd/types/xsimd_neon_uint8.hpp
Notes are in the commit messages.
GCC no longer needs `-flax-vector-conversion`.  I fixed the implicit casts.
In addition, I used intrinsics in `mul` for uint64 on NEON 32. The issue here is that both Clang and GCC will incorrectly switch to scalar multiply, which is slower than the pure NEON alternative on ARMv7a. 
I would like someone to benchmark the modified `mul` code on an aarch64 device. I have it disabled because I assume it would be slower like the same approach on x86_64, but I could be wrong. 
I commented the equivalent C code in the function, as the intrinsics can be a little hard to follow. The intrinsics are required, though, as it is apparently impossible without them.
=> Fix lax vector conversion and GCC/Clang multiply bug.

include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp
Hi there,
There's a correction (again, sorry) for batch_bool<T,.>::operator[] for avx/sse double/float: a direct reinterpret_cast<&...> may break the implicit aliasing rules of the modern optimizing compilers. For instance, with g++, batch_bool<T,.>::operator[] works now with -ffast-math and -O6 (it was actually not always the case before). Works also with msvc.
Best regards.
=> Potential aliasing issue

include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp
Hi there,
As discussed in a previous pull request, there's a proposition where for AVX and SSE, `batch_bool<floating point,N>` attributes become unions. These unions contain either a SIMD type or an array to allow selection by index (and then to be able to forward `array.begin()`, `array.end()`, etc...).
It has been done only for batch_bool, floating points and AVX/SSE. I guess that to be coherent, it would be nice to do the same thing for generic batches and other SIMD instruction sets... but I wanted to be sure to be on the right track before changing everything (and exposing the world to bad things :) ).
For `batch_bool`, taking an array of ints solves the problem with `-ffast-math` (which changes the conversion value of `nan` to `bool`). In this case, the potential aliasing issue is …
=> union { __mxxxd reg; array<int_type,N> arr; } for batch_bool, AVX/SSE

include/xsimd/types/xsimd_neon_double.hpp
Fixing an issue (apparently a typo) that triggered a warning about a wrong combination of signed and unsigned ARM NEON vectors.
=> Fixing wrong combination of signed/unsigned intrinsics

include/xsimd/stl/algorithms.hpp, test/xsimd_algorithms.cpp
I've add another missing STL algorithm to the algorithm header: `reduce` along with unit tests.
=> Adding stl style reduce algorithm with tests.

include/xsimd/stl/algorithms.hpp
```
C:\[...]\include\xsimd/stl/algorithms.hpp(69): error C2995: 'void xsimd::
transform(I1,I2,O1,UF &&)': function template has already been defined [...]
C:\[...]\include\xsimd/stl/algorithms.hpp(128): error C2995: 'void xsimd:
:transform(I1,I2,I3,O1,UF &&)': function template has already been defined [...]
```
Please consider releasing a new version right after merging this...
=> Add missing include guard for algorithms.hpp

include/xsimd/stl/algorithms.hpp
It causes exceptions in MSVC STL in Debug config when debug
iterators are enabled (default).
=> Do not dereference end iterators

include/xsimd/memory/xsimd_aligned_allocator.hpp
=> Removed std::allocator memeber deprecated in C++17

include/xsimd/math/xsimd_rem_pio2.hpp
`ONCE0` is defined, but not undefined. this causes possible name clashes downstream
=> rem_pio2: undef `ONCE0`

include/xsimd/config/xsimd_instruction_set.hpp, include/xsimd/types/xsimd_avx512_int32.hpp, include/xsimd/types/xsimd_avx512_int64.hpp, include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp, test/xsimd_basic_test.hpp
The signed integer right shift operators (operator>>) for SSE, AVX, and AVX512 use the logical right shift intrinsics, not the arithmetic right shift intrinsics. This results in incorrect shift result for negative numbers and is also inconsistent with the neon right shift operators which correctly use the signed right shift intrinsics.
I have also modified the basic integer test to make every second test value negative when testing signed integers in order to increase test coverage to negative numbers.
=> use arithmetic right shift SSE/AVX intrinsics for signed integer >>

include/xsimd/types/xsimd_avx512_bool.hpp
This caused avx512 int16_t and uint16_t unit tests to fail when avx512bw
was not enabled (only avx512f enabled)
=> Fix avx512_fallback_batch_bool constructor and load_values

include/xsimd/types/xsimd_avx512_int16.hpp, include/xsimd/types/xsimd_avx512_int8.hpp, include/xsimd/types/xsimd_avx_int16.hpp, include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_avx_int8.hpp, include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp, include/xsimd/types/xsimd_sse_int8.hpp
This includes:
1. Using the abs intrinsics instead of the sign intrinsics for 8, 16,
and 32 bit arithmetic, e.g. _mm_abs_epi8/16/32 instead of
_mm_sign_epi8/16/32 (both are SSSE3), using _mm256_abs_epi8/16/32
instead of _mm256_sign_epi8/16/32 (both are AVX2).
2. Add 64 bit abs intrinsics that came with AVX512VL to SSE and AVX
3. Add guards around 8 and 16 bit AVX512 abs intrinsics that require
AVX512BL
=> Clean up abs implementation for Intel intrinsics

include/xsimd/config/xsimd_instruction_set.hpp, include/xsimd/types/xsimd_avx512_conversion.hpp, include/xsimd/types/xsimd_avx_conversion.hpp, include/xsimd/types/xsimd_base.hpp, include/xsimd/types/xsimd_neon_conversion.hpp, include/xsimd/types/xsimd_sse_conversion.hpp, test/xsimd_basic_test.cpp, test/xsimd_basic_test.hpp, test/xsimd_test_utils.hpp
Hi guys. I really hope you're ok with me adding such a big new feature.
I think this is a nice addition to the API and I actually have a use
case for this on a personal project I'm working on.
Currently there is support for converting floats to ints (to_int) and
ints to floats (to_float) but there is no way to do the equivalent of a
static_cast, i.e. request a value of some specific type be converted to
another specific type. The new batch_cast function will allow you to do
this and leverage any intrinsics that exist to accelerate that
conversion.
Example usage:
```C++
xsimd::batch<int32_t, 4> b_int(...);
xsimd::batch<float, 4> f_float = xsimd::batch_cast<float>(b_int);
```
Let me know if you would prefer to have the batch_cast template type to
take a full batch type instead of just the …
=> Add new batch_cast function to expand support for type conversion

include/xsimd/config/xsimd_instruction_set.hpp, include/xsimd/types/xsimd_avx512_int16.hpp, include/xsimd/types/xsimd_avx512_int32.hpp, include/xsimd/types/xsimd_avx512_int64.hpp, include/xsimd/types/xsimd_avx512_int8.hpp, include/xsimd/types/xsimd_avx512_int_base.hpp, include/xsimd/types/xsimd_avx_int16.hpp, include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_avx_int8.hpp, include/xsimd/types/xsimd_avx_int_base.hpp, include/xsimd/types/xsimd_neon_int16.hpp, include/xsimd/types/xsimd_neon_int32.hpp, include/xsimd/types/xsimd_neon_int64.hpp, include/xsimd/types/xsimd_neon_int8.hpp, include/xsimd/types/xsimd_neon_uint16.hpp, include/xsimd/types/xsimd_neon_uint32.hpp, include/xsimd/types/xsimd_neon_uint64.hpp, include/xsimd/types/xsimd_neon_uint8.hpp, include/xsimd/types/xsimd_sse_int16.hpp, include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp, include/xsimd/types/xsimd_sse_int8.hpp, include/xsimd/types/xsimd_sse_int_base.hpp, test/xsimd_basic_test.hpp
I have implemented the remaining shift operators, primarily the vector shift ones. I have also provided intrinsics-based implementations for some shift operators where single intrinsics don't exist, e.g. the int8 Intel ones.
The final change I made was to the AVX512 shift intrinsics. I narrowed down the requirement to know the shift arg at compile time to a limitation that only exists in GCC 6. I believe this is a compiler bug as:
1. other versions of the same compiler plus all other compilers all support a variable arg (thanks compiler explorer), and
2. the underlying AVX512 instructions support getting the shift arg from a register. For example, _mm512_slli_epi32 maps to the vpslld instruction, and as per this documentation, there is a version of the instruction that takes an immediate …
=> Implement remaining vector shift operators

include/xsimd/types/xsimd_sse_conversion.hpp
Extra semicolons placed at the end of macros usage, this leads to an error if compiled with GCC 4.9 with -pedantic flag.
=> Remove extra semicolons in macros

include/xsimd/types/xsimd_avx_conversion.hpp
Others extra semicolons placed at the end of macros usage, this leads to an error if compiled with GCC 4.9 with -pedantic flag.
=> Remove others extra semicolons in macros

include/xsimd/types/xsimd_utils.hpp
This PR addresses a very minor problem: Inside a function there is a shadowing declaration from the higher context. This PR renames the local declaration to clarify the intended meaning.
=> xsimd_utils.hpp: Renamed a shadowing variable inside a macro

include/xsimd/types/xsimd_sse_int8.hpp
Required for std::numeric_limits
=> Fix missing include for gcc-11

docs/environment.yml
Documentation only, no need to wait for CI.
=> Pins breathe 4.16.0 in docs/environment.yml

include/xsimd/types/xsimd_avx512_conversion.hpp, include/xsimd/types/xsimd_base.hpp
These two patches 1) fix `-Wpedantic` warnings about unnecessary semicolons and 2) avoid dereferencing a type-puned pointer, which can break strict aliasing.
=> Eliminate -Wpedantic warnings and avoid dereferencing type-punned pointer.

include/xsimd/types/xsimd_neon_bool.hpp, test/xsimd_basic_test.hpp
Also improve the bool reduction tests, so as to exhibit the bug.
=> Fix any() and all() on Neon

include/xsimd/types/xsimd_avx512_int16.hpp, include/xsimd/types/xsimd_avx512_int8.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_avx_int8.hpp
Fix warnings using either `$ g++ -Wshadow=compatible-local` or `$ clang++ -Wshadow-uncaptured-local`.
```bash
[...]/include/xsimd/types/xsimd_avx_int8.hpp:413:62: warning: declaration of ‘int32_t rhs’ shadows a parameter [-Wshadow=compatible-local]
413 |         return avx_detail::shift_impl([](int8_t val, int32_t rhs) { return val << rhs; }, lhs, rhs);
|                                                      ~~~~~~~~^~~
[...]/include/xsimd/types/xsimd_avx_int8.hpp:408:79: note: shadowed declaration is here
408 |     inline batch<int8_t, 32> operator<<(const batch<int8_t, 32>& lhs, int32_t rhs)
|                                                                       ~~~~~~~~^~~
```
=> Rename shadowing variables

test/test_utils.hpp
Missing angle bracket and failed to build on Arm64 when `-DBUILD_TESTS=ON`:
```
In file included from /home/linux/yuqi/xsimd/test/test_algorithms.cpp:12:
/home/linux/yuqi/xsimd/test/test_utils.hpp:678:38: error: template argument 2 is invalid
678 |                                      batch<std::complex<double, 2>
|                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
679 | #ifdef XSIMD_ENABLE_XTL_COMPLEX
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
680 |                                      ,
|                                      ~
681 |                                      batch<xtl::xcomplex<double>, 2>
|                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
682 | #endif
| ~~~~~~
683 | #endif
| ~~~~~~
684 |     >;
|     ~
```
=> Fix build issue in Arm64 for missing the angle bracket

include/xsimd/types/xsimd_complex_base.hpp, test/test_batch_complex.cpp
=> Support creating complex batch from real pointer

include/xsimd/types/xsimd_base.hpp, include/xsimd/types/xsimd_neon_double.hpp, include/xsimd/types/xsimd_neon_float.hpp, include/xsimd/types/xsimd_neon_int16.hpp, include/xsimd/types/xsimd_neon_int32.hpp, include/xsimd/types/xsimd_neon_int64.hpp, include/xsimd/types/xsimd_neon_int8.hpp, include/xsimd/types/xsimd_neon_uint16.hpp, include/xsimd/types/xsimd_neon_uint32.hpp, include/xsimd/types/xsimd_neon_uint64.hpp, include/xsimd/types/xsimd_neon_uint8.hpp, include/xsimd/types/xsimd_sse_double.hpp, include/xsimd/types/xsimd_sse_float.hpp, include/xsimd/types/xsimd_sse_int16.hpp, include/xsimd/types/xsimd_sse_int32.hpp, include/xsimd/types/xsimd_sse_int64.hpp, include/xsimd/types/xsimd_sse_int8.hpp
Add zip_hi/zip_lo for shuffling operations mentioned in issues#412.
`test_xsimd` is passed Arm64 & x86:
```
Instruction set: ARMv8 64bit Neon
[==========] Running 369 tests from 85 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from algorithms
[ RUN      ] algorithms.binary_transform
[       OK ] algorithms.binary_transform (0 ms)
[ RUN      ] algorithms.unary_transform
......
....
..
snip
...
[----------] 2 tests from trigonometric_test/arm_double, where TypeParam = xsimd::batch<double, 2ul>
[ RUN      ] trigonometric_test/arm_double.trigonometric
[       OK ] trigonometric_test/arm_double.trigonometric (3 ms)
[ RUN      ] trigonometric_test/arm_double.reciprocal
[       OK ] trigonometric_test/arm_double.reciprocal (2 ms)
[----------] 2 tests from …
```
=> Add zip_hi/zip_lo for shuffling operations

.appveyor.yml, include/xsimd/math/xsimd_rounding.hpp, include/xsimd/types/xsimd_avx512_double.hpp, include/xsimd/types/xsimd_avx512_float.hpp, include/xsimd/types/xsimd_avx512_int16.hpp, include/xsimd/types/xsimd_avx512_int32.hpp, include/xsimd/types/xsimd_avx512_int64.hpp, include/xsimd/types/xsimd_avx512_int_base.hpp, include/xsimd/types/xsimd_avx_conversion.hpp, include/xsimd/types/xsimd_sse_conversion.hpp
=> FixAVX 512 build under VS2015

examples/mandelbrot.cpp
On Windows, using msys2/mingw64 compiler, examples always crash with SEGV on ___chkstk_ms. This can be avoid with making static variable.
=> Fix segmentation fault on mingw

include/xsimd/types/xsimd_avx512_double.hpp, include/xsimd/types/xsimd_avx512_float.hpp, include/xsimd/types/xsimd_avx512_int16.hpp, include/xsimd/types/xsimd_avx512_int32.hpp, include/xsimd/types/xsimd_avx512_int64.hpp, include/xsimd/types/xsimd_avx512_int8.hpp, include/xsimd/types/xsimd_avx_double.hpp, include/xsimd/types/xsimd_avx_float.hpp, include/xsimd/types/xsimd_avx_int16.hpp, include/xsimd/types/xsimd_avx_int32.hpp, include/xsimd/types/xsimd_avx_int64.hpp, include/xsimd/types/xsimd_avx_int8.hpp, include/xsimd/types/xsimd_fallback.hpp, test/CMakeLists.txt, test/test_shuffle_128.cpp
As discussed in https://github.com/xtensor-stack/xsimd/pull/434,
this PR is to add zip_lo/hi test cases.
The related test cases are implemented just for Neon/SSE(128bit).
=> Add zip_lo/hi test cases for shuffling 128bit data.

include/xsimd/memory/xsimd_aligned_allocator.hpp
7a4fc55 added uses of the assert macro without including the cassert
header
=> fix missing cassert header

include/xsimd/math/xsimd_numerical_constant.hpp, test/CMakeLists.txt, test/test_numerical_constant.cpp
As a side effect, detect a defect in xsimd::minposval
Fix #474
=> Minimal testing of xsimd_numerical_constant

docs/source/basic_usage.rst
Thanks for the great library!
Add the `arch` namespace needed to get access to `avx::batch`.
It looks like the README uses `batch<double, 4>`. If that's preferred I can update the PR to do that instead.
=> Add extra namespace in Basic Usage example

include/xsimd/types/xsimd_avx512_conversion.hpp, include/xsimd/types/xsimd_avx_conversion.hpp, include/xsimd/types/xsimd_fallback.hpp, include/xsimd/types/xsimd_neon_conversion.hpp, include/xsimd/types/xsimd_sse_conversion.hpp, test/test_conversion.cpp
Background( in #475 ): 
- In Arrow use cases scenario (xsimd as the 3rd party simd library),  we'd like to cast xsimd::batch<uint8_t, 16> to xsimd::batch<uint32_t, 4> for operating some fixed size of shared data buffer. 
For this fixed size of shared data buffer, data usually are regarded as `unsigned`. So the PR is just for u8,u16, u32 and u64.
- In x86,  the simd data structures are  `__m128i` / `__m256i `/ `__m512i`.
It's correct to leverage the `static_cast` to  cast `uint8 * N_u8` to `uint16 * N_u16` , `uint32 * N_u32` `and uint64 * N_u64`, but it failed in Arm64.
- In xsimd, [XSIMD_BITWISE_CAST_INTRINSIC](https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/types/xsimd_base.hpp#L389) (`#define XSIMD_BITWISE_CAST_INTRINSIC(T_IN, N_IN, T_OUT, N_OUT, INTRINSIC)`) is used …
=> Implement uint8 casting functions

include/xsimd/math/xsimd_power.hpp
non-constexpr `static const` variable initialization overhead (guard variable and checking).
removing the `static` keyword removes the overhead
see https://godbolt.org/z/3b8sGnhcj.
=> Fix non-constexpr static const variable overhead

include/xsimd/types/xsimd_avx512_conversion.hpp, include/xsimd/types/xsimd_avx_conversion.hpp, include/xsimd/types/xsimd_base.hpp, include/xsimd/types/xsimd_neon_conversion.hpp, include/xsimd/types/xsimd_sse_conversion.hpp, test/test_bitwise_cast.cpp
The existing bitwise_cast implementation only had support for casting
between floats, doubles, int32s and int64s. This change adds support
for casting to/from int8s and int16s as well as all the unsigned ints.
I chose to add explicit instantiations for all the different
permutations as opposed to using partial template specialisation or
SFINAE as I wanted to keep the implementation simple despite that
resulting in a very verbose implementation.
=> Add remaining bitwise_cast permutations

include/xsimd/math/xsimd_fp_manipulation.hpp, include/xsimd/math/xsimd_logarithm.hpp, include/xsimd/types/xsimd_int_conversion.hpp
// fexps are 8/11-bit numbers. so we can down-cast to int16_t/int32_t then do the job
=> optimize logarithm exponent int-to-float conversion

include/xsimd/config/xsimd_config.hpp
the config file is missing `XSIMD_VERSION_*`  which are still needed in the CMakeLists.
Not sure if 8.0.0 is the correct version of master
=> added XSIMD_VERSION_* defines back to config

include/xsimd/types/xsimd_avx2_register.hpp, include/xsimd/types/xsimd_avx512bw_register.hpp, include/xsimd/types/xsimd_avx512cd_register.hpp, include/xsimd/types/xsimd_avx512dq_register.hpp, include/xsimd/types/xsimd_avx512f_register.hpp, include/xsimd/types/xsimd_avx_register.hpp, include/xsimd/types/xsimd_fma3_register.hpp, include/xsimd/types/xsimd_fma5_register.hpp, include/xsimd/types/xsimd_neon64_register.hpp, include/xsimd/types/xsimd_neon_register.hpp, include/xsimd/types/xsimd_sse2_register.hpp, include/xsimd/types/xsimd_sse3_register.hpp, include/xsimd/types/xsimd_sse4_1_register.hpp, include/xsimd/types/xsimd_sse4_2_register.hpp, include/xsimd/types/xsimd_ssse3_register.hpp, test/test_arch.cpp
=> Support `name()` method for arch

examples/mandelbrot.cpp
this makes the Mandelbrot example run again.
I refactored the code a bit such that it runs for all supported archs.
Downside of the generic approach is that I rely on `typeid(arch).name()` to print the name of the arch.
One could add a name function to the arch itself.
smth like 
```c++
struct avx2 : avx
{
static constexpr std::string name() {return "avx2";}
static constexpr bool supported() { return XSIMD_WITH_AVX2; }
static constexpr bool available() { return true; }
static constexpr unsigned version() { return generic::version(2, 2, 0); }
};
```
=> Refactor examples

include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/config/xsimd_config.hpp
I'm building apache arrow with latest xsimd and met with many errors
when using clang and enabling avx512. This patch fixes the issues.
=> Fix avx512 build error from clang

include/xsimd/memory/xsimd_aligned_allocator.hpp
Build apache arrow on fedora-33 with clang-11 failed with below xsimd error:
xsimd_ep/src/xsimd_ep-install/include/xsimd/types/../memory/xsimd_aligned_allocator.hpp:345:15:
error: no member named 'allocator' in namespace 'std'; did you mean 'alloca'?
std::allocator<T>
^~~~~
=> Adding missing header "memory"

include/xsimd/arch/xsimd_ssse3.hpp, include/xsimd/config/xsimd_arch.hpp
Missing default template argument and invalid recursion...
Fix #557
=> Fix extract_pair implementation on SSSE3

include/xsimd/config/xsimd_config.hpp, test/test_select.cpp
There are some msvc build warnings in current xsimd code. It may block
adoption of xsimd by some projects (e.g., apache arrow) if they treat
compiler warnings as errors. As xsimd is header only, it's not easy to
build xsimd separately to ignore the warnings.
=> Fix msvc build warnings

include/xsimd/types/xsimd_batch.hpp, include/xsimd/types/xsimd_register.hpp, include/xsimd/types/xsimd_traits.hpp, test/test_batch_complex.cpp, test/test_traits.cpp
=> Added missing traits for batch of complex

include/xsimd/arch/generic/xsimd_generic_logical.hpp, include/xsimd/types/xsimd_batch.hpp, test/test_batch.cpp
=> Implemented operator&& and operator|| for batch

include/xsimd/config/xsimd_config.hpp
MSVC annoyingly does not define `__SSE2__` at all, instead relying on the fact that:
- SSE2 is supported unconditionally for x86-64 targets (which you already handle)
- SSE2 is opt-in for x86-32 targets and is detected by checking [`_M_IX86_FP >= 2`](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160`)
This PR adds the requisite checks to handle the 32-bit target scenario on MSVC.
=> Fix SSE2 not being detected correctly on MSVC for 32-bit targets

benchmark/CMakeLists.txt
This PR fixes https://github.com/xtensor-stack/xsimd/issues/579. Should be fairly safe to merge.
=> Fixed a minor spelling mistake in 'xsimd_INCLUDE_DIRS'

include/xsimd/arch/generic/xsimd_generic_details.hpp, include/xsimd/arch/xsimd_neon.hpp, test/test_batch_cast.cpp
Fixes #626 
I'm not sure about formatting; it would be helpful to have a clang-format config.
The value of a test for this is a bit questionable since you can't see what implementation will actually use, so feel free to skip that.
=> fix fast_cast selection

test/CMakeLists.txt
Failed to `cmake `with clang-10/11/12 when enabling '-DBUILD_TESTS' on Arm64:
```
Run Build Command(s):/usr/bin/make cmTC_0043d/fast && /usr/bin/make -f CMakeFiles/cmTC_0043d.dir/build.make CMakeFiles/cmTC_0043d.dir/build
make[1]: Entering directory '/home/builder/xsimd/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_0043d.dir/src.cxx.o
/usr/bin/clang++-10    -march=native -DHAS_CPP11_FLAG   -std=c++11 -o CMakeFiles/cmTC_0043d.dir/src.cxx.o -c /home/builder/xsimd/build/CMakeFiles/CMakeTmp/src.cxx
clang: error: the clang compiler does not support '-march=native'
make[1]: *** [CMakeFiles/cmTC_0043d.dir/build.make:66: CMakeFiles/cmTC_0043d.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/builder/xsimd/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_0043d/fast] …
```
=> Fix Arm64 Clang build issues when enabling '-DBUILD_TESTS'

include/xsimd/arch/xsimd_fma3.hpp, include/xsimd/config/xsimd_config.hpp
=> Enables support for FMA when AVX2 is detected on Windows

include/xsimd/config/xsimd_arch.hpp, include/xsimd/config/xsimd_cpuid.hpp, include/xsimd/types/xsimd_register.hpp, test/test_arch.cpp
See #632, #633 and #634.
This doesn't cover the documentation or cmake aspects of #633; i think that's a separate job.
I'm not totally sure about the consequences of "add explicit check for architecture support in batch"; it could make for more mysterious error messages if simd_register is used directly for some reason, but I think it'll be alright.
=> Fix dispatch issues

include/xsimd/config/xsimd_arch.hpp, include/xsimd/types/xsimd_generic_arch.hpp, test/test_arch.cpp
This is a follow-on from #635; this is useful when using per-architecture compilation and dynamic dispatch, as the required alignment when allocating data can be greater than the alignment of the default architecture.
=> add alignment helper to arch_list

include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx2.hpp
Previously, AVX2 `gt` was implemented, but `lt` fell back to the AVX `lt`, which is implemented with SSE2 instructions.
generic_logical has the following mappings:
- `gt` -> `lt`
- `ge` -> `le`
- `le` -> `lt || eq`
so it seems best to just implement `eq`, `lt`, and `le` if it's available.
I've had a brief look at the SSE and NEON comparison code and they don't seem to be affected by this.
It's tempting to go through and delete all the `gt` and `ge` implementations as they don't seem to add anything, but I feel like I might be missing something.
Here's an example showing the issue: https://gcc.godbolt.org/z/Gd3K9WfTG
=> improve code generated for AVX2 signed integer comparisons

include/xsimd/stl/algorithms.hpp, test/test_algorithms.cpp
This fixes #652. New tests are included.
=> Fix xsimd::transform for complex types.

include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx2.hpp, test/CMakeLists.txt, test/test_shuffle.cpp
As a workaround, rely on cast from float to support epi32 and epi64 on AVX.
Should fix #668
=> Only use _mm256_unpacklo_epi<N> on AVX2

docs/source/api/batch_manip.rst, docs/source/api/math_index.rst, docs/source/api/xsimd_batch.rst, docs/source/index.rst
So that arithmetic operators end at the same level as mathematical functions.
=> Update layout of the documentation

include/xsimd/config/xsimd_config.hpp
To achieve that goal, they must manually set -DXSIMD_WITH_FMA3_<arch>=0
Error if that flag is incompatible with actual compiler support.
Fix #643
=> Leave to msvc users the opportunity to manually disable FMA3 on AVX

test/CMakeLists.txt
In Android builds, the cmake make toolchain sets the correct compiler optimization flags.
=> Do not set compiler options in Android builds in tests

include/xsimd/arch/generic/xsimd_generic_logical.hpp, include/xsimd/types/xsimd_batch.hpp, test/test_basic_math.cpp
It is tempting to build a batch from a memory address, but that's not supported,
load_aligned or load_unaligned provide that feature instead.
As C++ conversion rule would still accept that constructor as T* is convertible
to bool which is convertible to T, mark these constructors explicitly deleted.
Fix #602
=> Prevent building invalid batch due to implicit conversion

include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_sse4_1.hpp
This PR adjusts the check that was added in #690 to:
- account for MSVC only (_WIN32 also implies MSYS compilers, such as GCC and Clang)
- block usage of the intrinsics only on MSVS 2015 and earlier, which lack the definition.
=> insert: allow intrinsics to be used for Windows

include/xsimd/arch/generic/xsimd_generic_details.hpp, include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx512dq.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_neon64.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/types/xsimd_api.hpp, test/test_rounding.cpp
:wave:
Again re #706, this is the rounding function that returns integers instead of floating-point numbers. I've renamed it appropriately, since there's already a `nearbyint` function that works similarly.
Rationale for this function: https://godbolt.org/z/q4rc6dvW3
Fixes #623
=> Add xsimd::nearbyint_as_int

test/test_utils.hpp
This PR lifts the precision limit for Xcode-built tests only.
Fixes #648
Closes #695
=> Allow a bit more of wiggling room for AppleClang

include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_avx2.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/types/xsimd_batch.hpp, include/xsimd/types/xsimd_utils.hpp, test/test_load_store.cpp
Hi!
This PR is to propose adding five new functions to xsimd. I've used these in the (still WIP) port from Vc to xsimd, which you can see [here](https://invent.kde.org/graphics/krita/-/merge_requests/1404).
These functions are *(crossing out already upstreamed ones, check the mentions)*:
- ~~`xsimd::reciprocal`: calculates the approximate reciprocal of the SIMD register.~~
- ~~`xsimd::none`: a typo-free way to say `!xsimd::any` more clearly.~~
- `xsimd::gather` and `xsimd::scatter`: for <AVX512F, templates gathering using the new `xsimd::insert` function. (It will also take advantage of #691 when it's fixed)
- ~~`xsimd::round_to_even`: uses intrinsics to achieve fast rounding to even *integers*.~~
~~These do not include tests yet, as I'd like first to gather some feedback, especially …
=> Add gather/scatter functions to xsimd::batch

.azure-pipelines/azure-pipelines-win.yml
👋 
Currently, the clang-cl build in Azure Pipelines is a dud-- it still uses MSVC 2022 because CMake cannot find the conda-installed compiler. This MR changes the workflow definition to use ClangCL as included in MSVS and removes some unused steps.
=> Azure Pipelines: fix targeting clang-cl

include/xsimd/arch/generic/xsimd_generic_details.hpp, include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/xsimd_avx512dq.hpp, include/xsimd/arch/xsimd_neon64.hpp, test/test_rounding.cpp, test/test_utils.hpp
This PR fixes the semantics of nearbyint_as_int on Arm. I made a typo in the AVX512DQ version too.
You'll notice that I added a guard around the NEON64 version; I've seen online that the codegen of GCC simply doesn't return the expected results, but Clang's does.
This PR depends on #726, which is why you'll see extraneous commits. They'll be gone once that one is merged.
See #721
=> Fix nearbyint_as_int test on Arm

include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_neon.hpp, include/xsimd/types/xsimd_batch.hpp, include/xsimd/types/xsimd_utils.hpp, test/CMakeLists.txt
:wave: 
This introduces small fixes and quality-of-life optimizations I made as part of my debugging.
- Made the tests buildable on MSYS Clang
- Arm's type size SFINAE have been factored out for better availability
- Changed the internals of gather/scatter to take a single index in the template (the current element).
The last change includes a small refactor to move the `get` implementation inside `generic_memory`, thus making it style-wise more compliant and mistake-proof.
=> Slight optimization to gather/scatter + related fixes

include/xsimd/arch/xsimd_avx.hpp
:wave:
This PR adds support for swizzling 32-bit and 64-bit integers in AVX by bitwise_casting to float and double respectively.
(Includes #730 as I'm using the two together in one of my Krita tests.)
=> Support swizzling int32_t and int64_t in AVX

include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/types/xsimd_api.hpp, test/test_batch_complex.cpp
I often run into cases where I need to multiply two complex batches, but only take the real or imaginary part, e.g.
```cpp
batch<std::complex<float>> a;
batch<std::complex<float>> b;
auto y = real(a * b);
```
In this case, doing the full multiply operation is somewhat wasteful, since half of the operation ends up getting thrown away.
This PR adds `xsimd::mul_real()` and `xsimd::mul_imag()` to compute this result without the wasted computations.
=> Add real and imaginary complex multiplication

examples/CMakeLists.txt, include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx2.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/types/xsimd_batch.hpp, include/xsimd/types/xsimd_utils.hpp, test/test_error_gamma.cpp
:wave: 
I finished the xsimd port of our app, and I discovered that Vc accelerates narrowing gathers of particular types. xsimd doesn't have these primitives, so I looked at the assembly and ported them here.
This PR also removes dead code that got introduced by mistake in #730 .
(Setting as draft because I'd like to check if I can add choices in SSE-land, as well as widening options.)
=> Accelerate gathers

include/xsimd/arch/xsimd_sse4_1.hpp
👋 
I found a very specific case CI didn't cover: if the MSVC version is new enough (2019/22) and it compiles with `/arch:SSE2`, hence targeting up to SSE4.2, it will attempt to use `_mm_insert_epi64`. But according to [the docs](https://docs.microsoft.com/en-us/cpp/intrinsics/x86-intrinsics-list?view=msvc-170), this particular intrinsic isn't available on x86 platforms.
This PR makes sure we don't try to use this intrinsic on these particular builds.
=> Fix x86-only build on MSVC

include/xsimd/arch/xsimd_avx512bw.hpp
:wave:
This PR is to fix an oversight in #724, in recent enough Clang versions `#include <array>` isn't implied by `type_traits`.
I tested this with MSYS Clang 14.0.3 on the CLANG32 and CLANG64 ABIs.
=> Fix usage of unincluded std::array in avx512bw

CMakeLists.txt, cmake/JoinPaths.cmake, xsimd.pc.in
xsimd is a header-only library, so libdir is not useful
Fix #748
=> Fix libdir entry in xsimd.pc

include/xsimd/xsimd.hpp
The proper way to check if the compiler is Clang or not, is to [check if `__clang__` is defined](https://stackoverflow.com/a/2658480/12591388). I updated the preprocessor directives around `XSIMD_NO_DISCARD` to check for `__clang__` as well.
=> Made it so that clang also warns on unused results.

.azure-pipelines/azure-pipelines-linux-clang.yml, .azure-pipelines/azure-pipelines-linux-gcc.yml, .azure-pipelines/unix-build.yml, CMakeLists.txt, docs/source/api/available_wrappers.rst, examples/mandelbrot.cpp, test/test_arch.cpp
Remove all obsolete reference to XSIMD_ENABLE_FALLBACK
Related to #756
=> There's no fallback implementation anymore, don't document it

include/xsimd/types/xsimd_register.hpp
I fixed the TODO, which said that using [`std::add_const`](https://en.cppreference.com/w/cpp/types/add_cv) and [`std::add_lvalue_reference`](https://en.cppreference.com/w/cpp/types/add_reference) is the preferred of building the `requires_arch` predicate.
I also removed the comment about the possible clash with the C++20 [`requires` keyword](https://en.cppreference.com/w/cpp/keyword/requires), as it is not a concern: The keyword is `requires`, so it does not clash with `requires_arch`.
=> Fixed a TODO.

include/xsimd/types/xsimd_batch.hpp
=> Properly static_assert when trying to instantiate a batch of xtl complex

include/xsimd/arch/xsimd_neon64.hpp
I noticed this was missing. On clang at least this still produces two calls to FADDP, but without an extract instruction present in the Neon32 implementation
=> Add NEON64 hadd for single-precision floats

include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/types/xsimd_api.hpp, test/test_batch_complex.cpp
This reverts commit cabcecf49116131144ec43d16551643a94198bb7. As suggested by @serge-sans-paille in #740.
=> Revert "Add real and imaginary complex multiplication"

test/test_batch_float.cpp
:wave:
This PR fixes #757 by setting up the `rsqrt` test with the documented relative error from Intel/AMD.
(For future reference: see https://news.ycombinator.com/item?id=23891810)
Fixes #757
=> rsqrt: account for AMD vs. Intel inconsistency in RCPPS relative error

include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx512f.hpp, test/test_xsimd_api.cpp
Fixes issue #805, where neq returns false for  x != Nan , where x is any valid floating point value.
=> Ensure Neq confirms to IEEE 754.

include/xsimd/arch/xsimd_sve.hpp, include/xsimd/config/xsimd_arch.hpp, include/xsimd/types/xsimd_sve_register.hpp
When linking two compilation units compiled with different sve length (e.g. to
support dynamic dispatch) current implementation use the same arch type for
different width, which leads to various linkage / runtime error.
Fix that by using a size-dependent type.
=> Fix potential ABI issue in SVE support

include/xsimd/arch/xsimd_scalar.hpp
=> Disable fast exp10 on OSX

include/xsimd/types/xsimd_batch.hpp
This should help understanding segfaults in debug builds.
=> Assert on unaligned memory when calling aligned load/store

include/xsimd/types/xsimd_traits.hpp, test/test_load_store.cpp
I understand the issue with char being either signed or unsigned, but
load_as<char>
not returning a
batch<char>
is too surprising--and currently leads to compile error anyway.
=> Do not specialize the behavior of simd_return_type for char

include/xsimd/types/xsimd_batch.hpp, test/CMakeLists.txt, test/test_explicit_batch_instantiation.cpp
These operators don"t make sens for floating point operation, so don't provide them.
Fix #792
=> Only provide % << and >> operators for integral batch types

include/xsimd/types/xsimd_generic_arch.hpp, test/test_arch.cpp
Currently when `xsimd::generic` is put in dispatch arch list as a catch-all fallback, it fails the version comparison because the `version()` function is missing.  Adding it allow us to use it in dispatch, as long as the implementation does not involve any batch operation.
Fix #638
=> Allow generic to be used in dispatch arch list

.github/workflows/linux.yml, include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/xsimd_avx512bw.hpp, include/xsimd/arch/xsimd_avx512dq.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/types/xsimd_avx512cd_register.hpp, test/test_shuffle.cpp
This enables avx512 f, er, cd, pf only, which should improve coverage of avx512 testing.
=> Enable CI for Intel's KNM architecture

include/xsimd/arch/xsimd_avx512dq.hpp, include/xsimd/arch/xsimd_avx512f.hpp
Thanks to @fritterhoff for pointing at the associated intrinsic. Fix #331
=> Use intrinsic instead of generic implementation of ldexp on avx512f

include/xsimd/config/xsimd_cpuid.hpp
From https://www.amd.com/system/files/TechDocs/24594.pdf page 596 ,and https://www.felixcloutier.com/x86/cpuid#fig-3-6 I see that the SSE2 flag comes from a different registry than the other flags. Does EDX correspond to reg[3] ?
=> Get SSE2 value from reg[3]

include/xsimd/types/xsimd_batch.hpp, test/test_batch.cpp, test/test_batch_bool.cpp
Instead of writing the actual scalar overloads, rely on the nice property of friend operators defined inline that allow for implicit conversion.
Fix #229
=> Provide and test comparison operators overloads that accept scalars

include/xsimd/types/xsimd_api.hpp, test/test_batch.cpp
Note that we don't support all register size, but we test it for scalar >= 32bits.
Fix #873
=> Provide a generic reducer

CMakeLists.txt, xsimdConfig.cmake.in
PR #788 fixes xtl lookup by adding the corresponding find_dependency call. However, there are still two issues remaining:
- If xtl is not found, the INTERFACE_LINK_LIBRARIES property will make CMake interpret "xtl" as a .lib, pass it as a -l flag, and cause the build to fail.
- If xtl is used, the required definition XSIMD_ENABLE_XTL_COMPLEX=1 is never passsed to downstream consumers.
This commit fixes both issues, ensuring that if xtl was required at compile time, the Config module with not load unless xtl is also found.
Fixes #869
=> Fix find_package(xsimd) for xtl enabled xsimd, reloaded

benchmark/CMakeLists.txt, benchmark/main.cpp, benchmark/xsimd_benchmark.hpp
* It's not benchmark's role to track warnings.
* Dump architecture name at the beginning of the bench
* Fix an incorrect dump of arch instead of benchmark name
=> Cleanup benchmark code

include/xsimd/arch/xsimd_scalar.hpp
The macro is not provided my Visual studio by default. The easiest and most straight forward way to support this is to expand its value.
=> Expand the value of M_LN10

include/xsimd/arch/xsimd_scalar.hpp, test/test_xsimd_api.cpp
Fixes #898
@serge-sans-paille it seems that it is the only way to get correct results of `exp10` on Windows.
=> back to slow implementation of exp10 on Windows on Windows

include/xsimd/arch/xsimd_neon.hpp, include/xsimd/arch/xsimd_neon64.hpp
Those are not strictly required (as in not providing them does not crash), but they (probably) help code generation.
=> Provide alignment hints on arm32 / aligned load

include/xsimd/arch/generic/xsimd_generic_details.hpp, test/test_conversion.cpp
A reinterpret_cast is usually the way to go. For the range of value when it's valid in C, we achieve the same behavior for batches.
Fix #735
=> Provide generic signed /unsigned type conversion

include/xsimd/config/xsimd_cpuid.hpp
Currently, SVE is not enabled in xsimd runtime dispatcher.
This PR adds the support for SVE runtime detecting.
=> Support SVE runtime dispatcher in xsimd

test/test_arch.cpp
This should prevent issues like #911 to be undetected in the future.
=> Test that we correctly detect the best arch at runtime

include/xsimd/arch/xsimd_scalar.hpp
xsimd is C++11 and hexadecimal floating point are C++17
=> Defer to (good) compiler the task of computing ln10

include/xsimd/types/xsimd_batch.hpp
Assignment operators like `operator|=`, `operator&=` and `operator^=` should not be const since the purpose of those operators is updating the object that defines the operator. With `const`, the following simple function does not compile:
```
void xsimd_or(xsimd::batch_bool<bool>& b1, xsimd::batch_bool<bool>& b2) {
b1 |= b2; 
}
```
=> Remove 'const' from batch_bool assignment operators

include/xsimd/arch/generic/xsimd_generic_complex.hpp, include/xsimd/arch/generic/xsimd_generic_details.hpp, include/xsimd/arch/xsimd_scalar.hpp, include/xsimd/types/xsimd_api.hpp, test/test_xsimd_api.cpp
Support xsimd::isfinite and xsimd::isinf, analogous to the existing xsimd::isnan implementation.
Extend tests so they also compile and run these functions with complex values.
=> Support isfinite/isinf for std::complex<X>

examples/mandelbrot.cpp, test/doc/explicit_use_of_an_instruction_set.cpp
They clutter the build output for no reason.
=> Fix minor warnings

CMakeLists.txt, test/CMakeLists.txt, test/doc/CMakeLists.txt
Basically so that -DENABLE_XTL_COMPLEX=On at configuration step implies -DXSIMD_ENABLE_XTL_COMPLEX=1 for the tests.
Fix #942
=> Add proper compile definition when XTL has been configured

include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/types/xsimd_api.hpp, test/test_batch_bool.cpp
Support for `eq` and `neq` operations was added for `bool_batch` in `xsimd_api.hpp`
=> Added missing boolean operators in xsimd_api.hpp

include/xsimd/types/xsimd_batch_constant.hpp, test/test_batch_constant.cpp
Add support for &&, ||, ^ and ! for batch_bool_constant. Add support for +, -, *, / and unary - for batch_constant.
=> Support basic operations on batch constant

include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/xsimd_sve.hpp, test/test_rounding.cpp
=> Test nearbyint_as_int using xsimd's scalar version instead of lround

include/xsimd/arch/generic/xsimd_generic_memory.hpp
Let the compiler do the heavy lifting when possible :-) Fix #926
=> Use __builtin_shufflevector for the generic implementation of shuffle

include/xsimd/arch/xsimd_sse2.hpp
The generic implementations of `sadd`, `ssub` and `hadd` were added in #952 and can be found [here](https://github.com/xtensor-stack/xsimd/blob/f27bbb85be2a60cedb0585c2306ea8405f49af90/include/xsimd/arch/generic/xsimd_generic_arithmetic.hpp#L183) and hence these TODO's can be addressed now through the generic implementation.
=> Implemented sadd, ssub & reduce_add through the generic implementation for xsimd_sse2

include/xsimd/arch/generic/xsimd_generic_details.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx2.hpp, include/xsimd/arch/xsimd_sse2.hpp
This remove duplicate code for various Intel implementation and should also help for #962.
=> Provide a generic version for float to uint32_t conversion

include/xsimd/arch/xsimd_wasm.hpp
The following operations would be implemented through the PR
=> Implemented few operations for the wasm instruction set

docs/source/basic_usage.rst
Made the warning message clearer
=> Fix grammar in basic_usage.rst

include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/xsimd_constants.hpp
This PR fix a bug than can occur with `-ffast-math`, where the compiler replace -0. values with 0. and therefore breaks the `bitofsign` function as well as several function (exp, sin, cos...) that make use of a bitwise `&` comparison with `constants::signmask`
To fix the `bitofsign` function I had to update it and stop using `minuszero` and use `signmask` instead. `minuszero` is therefore not used anywhere anymore and could maybe be deleted ?
I investigated a bit on how to do the same for clang but I didn't find a solution, and I wasn't able to reproduce the issue with a clang-based aarch64 compiler anyway.
This PR fixes #971
=> Fixed `constants::signmask` for GCC when using `ffast-math`

.github/toolchains/clang-riscv64-linux-gnu.cmake, .github/toolchains/gcc-riscv64-linux-gnu.cmake, .github/workflows/cross-rvv.yml, CMakeLists.txt, docs/Doxyfile, include/xsimd/arch/xsimd_isa.hpp, include/xsimd/arch/xsimd_rvv.hpp, include/xsimd/config/xsimd_arch.hpp, include/xsimd/config/xsimd_config.hpp, include/xsimd/config/xsimd_cpuid.hpp, include/xsimd/types/xsimd_all_registers.hpp, include/xsimd/types/xsimd_generic_arch.hpp, include/xsimd/types/xsimd_rvv_register.hpp, test/test_arch.cpp
Hello,
This adds support for the RISC-V architecture by using the RISC-V Vector Intrinsics [1]. I've added support for CI similarly to ARM SVE.
Thank you for your review!
Fixes https://github.com/xtensor-stack/xsimd/issues/503
[1] https://github.com/riscv-non-isa/rvv-intrinsic-doc
=> Add RISC-V Vector support.

include/xsimd/types/xsimd_avx512f_register.hpp, include/xsimd/types/xsimd_avx_register.hpp, include/xsimd/types/xsimd_batch.hpp, include/xsimd/types/xsimd_sse2_register.hpp, include/xsimd/types/xsimd_wasm_register.hpp
It was only supported on Intel architectures and wasm, for no clear reason. Provide a unified experience by enforcing batch_bool instead. If someone really wants a batch of bool, then use another type to store it, e.g. uint8_t.
Fix #945
=> Disable batch of bools, and suggest using batch_bool instead

.gitignore, CMakeLists.txt
An option `XSIMD_SKIP_INSTALL` is added to decide whether to install xsimd files. This can be useful when xsimd is used as an subproject.
To keep default behavior unchanged, the default value of this option is OFF. Developers can set `XSIMD_SKIP_INSTALL` to ON in order to skip xsimd installtion.
This pr implements #959
=> Add an option to skip installtion

include/xsimd/arch/xsimd_scalar.hpp
`exp10` and `exp10f` are missing on macOS before 10.9, which breaks building some dependents that use `xsimd` headers. Fix that.
=> xsimd_scalar.hpp: fix for missing exp10 on macOS < 10.9

include/xsimd/types/xsimd_batch.hpp
This leverage the specific layout of xsimd batch of complex.
=> Use fma and fms instruction when available to speedup complex multiply

include/xsimd/arch/xsimd_scalar.hpp
It returns invalid value for nan.
std::signbit appears to be missing on some Windows target for integral types.
=> Fix scalar version of signbit

include/xsimd/config/xsimd_cpuid.hpp
Some CPU vulnerability mitigations may disable AVX functionality on the hardware level via the XCR0 register. We should check that manually to verify that OS actually allows us to use this feature.
See https://bugs.kde.org/show_bug.cgi?id=484622
Fix #1025
=> Fix detection of SSE/AVX/AVX512 when they are explicitly  disabled by OS

include/xsimd/config/xsimd_cpuid.hpp, test/test_arch.cpp
Ideally the patch CPU detection code should also check if the length of SVE and RVV is actually supported by the current CPU implementation (i.e. ZCR_Elx.LEN register for SVE and something else for RVV), but I don't have such CPUs/emulators handy, so I cannot add such checks.
Given that xsimd::available_architectures().has() is a new feature of XSIMD13 and the length check has never been present in XSIMD, this bug is not a regression at least.
The patch also adds a unittest that reproduces the error the patch fixes
=> Fix xsimd::available_architectures().has() for sve and rvv archs

CMakeLists.txt
xsimd is header only library, so prefer arch-independed paths for cmake and pkg-config.
References:
* https://github.com/xtensor-stack/xtl/commit/d877d94836aff4d0f727acf3eaab8f4880ecb625
* https://github.com/xtensor-stack/xtensor/commit/7738389861044c9618c7d59fb7602f7dddc1df7f
=> Prefer arch-independed paths for install

include/xsimd/arch/generic/xsimd_generic_memory.hpp
__builtin_shuffle_vector -> __builtin_shufflevector
See https://clang.llvm.org/docs/LanguageExtensions.html#langext-builtin-shufflevector
Fix #1033
=> Fix __builtin_shufflevector name

docs/source/api/data_transfer.rst, include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_neon.hpp, include/xsimd/arch/xsimd_neon64.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/arch/xsimd_wasm.hpp, include/xsimd/types/xsimd_api.hpp, test/test_shuffle.cpp
=> Add support for xsimd::tranpose

test/CMakeLists.txt
While we're at it, fix option name typo XSIMD_DOWNLOAD_DOCTEST -> DOWNLOAD_DOCTEST
Fix #1056
=> Report status (failure or success) when downloading doctest .h

.github/workflows/cross.yml, include/xsimd/arch/xsimd_sse2.hpp, test/test_shuffle.cpp
... and test it, as well as other version.
=> sse2 version of xsimd::swizzle on [u]int16_t

include/xsimd/types/xsimd_api.hpp
Fix the missing `x` in the API docs for `batch_bool_cast` and `batch_cast`.
=> DOC: Remove a duplicated '\c' in two places.

include/xsimd/arch/generic/xsimd_generic_math.hpp, include/xsimd/arch/generic/xsimd_generic_memory.hpp, include/xsimd/types/xsimd_batch_constant.hpp, test/test_batch_constant.cpp, test/test_batch_manip.cpp, test/test_select.cpp, test/test_shuffle.cpp
So that we can use a default architecture, which is consistent with other API.
This is an API breaking change
=> Reorder make_batch_constant template arguments

include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_sse3.hpp
It's generally slower than the sse2 version due to a latency of 5 (!) for hadd_pd.
Related to #1107
=> Do not use hadd_pd to implement reduce_add

include/xsimd/arch/xsimd_avx.hpp
Just forward to sse after a split and a sum.
=> Faster reduce_add on avx

include/xsimd/arch/common/xsimd_common_math.hpp
=> Improve code generation for nearbyhint under -ffast-math

include/xsimd/arch/common/xsimd_common_memory.hpp, include/xsimd/arch/xsimd_avx.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/types/xsimd_batch.hpp, test/test_batch.cpp, test/test_batch_complex.cpp
This pr implements new first() function for batch types. It is an improvement from the currently used self.get(0) as first() uses intrinsics to extract the first element. Addresses inefficiencies mentioned in [issue #1133](https://github.com/xtensor-stack/xsimd/issues/1133).
I have only implemented for SSE/AVX/AVX512F architectures @serge-sans-paille will implement for other architectures.
I also haven't replace any .get(0) functions with first(). That needs to be done as well
=> Added first() function for SSE/AVX/AVX512F

include/xsimd/arch/xsimd_avx512bw.hpp, include/xsimd/arch/xsimd_avx512vbmi.hpp
* Use `_maskz_permutexvar` instead of `permute + and` on avx512bw, too
* Use `xsimd::make_batch_constant` and so `_mm512_set` instead of `_mm512_load(constexpr std::array)`
The first one is just a tiny optimization already done in the AVX512VBMI implementation.
The second patch makes it easier for the compiler to move this constants into the .text section. GCC is not affected, MSVC sadly is affected *a lot*. It used to generated 8 times `mov [rbp + N], const` with a single `vmovdqu32 zmm, [rdp]` afterwards - poor MSVC.... And worse for the store_forwarding unit....
=> avx512bw,vbmi: Optimize shift_left and shift_right.

include/xsimd/arch/xsimd_avx512f.hpp
There is no `_setr_` intrinsic for 16b and 8b types, so we have to flip the order ourself.
Honestly, there is a CI for catching such bugs. How can we missed to test this case?
=> MSVC/AVX512F: Fix batch_const with 16b and 8b integers.

docs/source/api/reducer_index.rst, docs/source/api/xsimd_batch_bool.rst, include/xsimd/types/xsimd_api.hpp
<strike>`count` is in the doxygen group `batch_reducers`, and it shows up below the table of reduction operators along with `reduce`, `reduce_add`, etc., in the generated HTML, so it might as well be in the table.</strike>
Updated the PR so now `count` is moved to the 'Reducers' section of the batch-bool docs.
=> DOC: Move 'count' to the batch-bool 'Reducers' section of the docs.

include/xsimd/arch/xsimd_avx512bw.hpp, include/xsimd/arch/xsimd_avx512f.hpp, include/xsimd/arch/xsimd_avx512vbmi.hpp, test/test_shuffle.cpp
With a fast path for N = 4*i and a split version else (inspired from avx512bw).
As the vpermd actually has the lower latency on some intel cpus compared to vpermw / vpermb, also use it instead of the avx512bw and avx512vbmi implementations if trivially possible.
Also reverse the order of the slow path for lower latency. It used to be:
```
SLR -> PERM ->
OR -> PERM
SLL         ->
```
Now the latency is reduced to:
```
SLR -> PERM ->
OR
SLL -> PERM ->
```
And it should now generate even better code on avx512bw with N=63 with only one PERM (as already done for N=1).
For N=16,32,48, it prefers vshufi32x4 over vpermd for lower latency on Zen4 and decreased register usage.
=> avx512f: implement slide_left and slide_right.

include/xsimd/arch/common/xsimd_common_math.hpp
It changes nothing for clang which has a nice shuffle optimizer, but it does help gcc a lot.
Somehow related to #1132
=> Generate a swizzle-friendly mask during generic reduction

include/xsimd/arch/xsimd_avx2.hpp, include/xsimd/arch/xsimd_avx512vbmi2.hpp, include/xsimd/arch/xsimd_sse2.hpp, include/xsimd/arch/xsimd_sse4_1.hpp
- Split some implementation that lived in sse4_1 while sse2 was a good home
- Avoid auxiliary function
=> Simplify load implementation from #1172
